title: KimKoding
author:
  name: Jason Kim
  email: kimyk96@gmail.com
description: >
  블로그 설명글
show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  kimyk96

header_pages:
- about.md
- links.md
- _posts/dir

theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag


 # more infos on https://github.com/jekyll/minima